### PR TITLE
Add some generative tests for Vmap and Umap

### PR DESCRIPTION
**Pull request by isaksky**
Added some generative tests for Vmap and Umap. 

It just randomly generates a sequence of actions (Add | Remove) to perform on an empty map, and applies them while maintaining a dictionary, then checks to see if they are equal afterwards. There is also one that does the same, except maintains a list of FSharp.Core.Maps, and checks equality going back.

Inspired by this approach, which found some bugs for people in the Clojure community:

https://github.com/ztellman/collection-check

If you add `(Verbose=True)` on the `Property`, you can see the tests it ran:

image

The tests pass for both Maps. :+1: .

### CODE REVIEW

**Comment by isaksky** [comment]
There are a few things I can improve here after some feedback from @cloudRoutine (code repetition, better way of getting the random values in, etc), so I can probably fix that tomorrow.

**Comment by bryanedds** [comment]
Looks good - I'll start working on the pull now!

**Comment by isaksky** [comment]
With my last commit, it found a problem with Umap:

image

The problem is not with the last reference, but with previous ones:

```
> let um : Umap<int,int> = Umap.ofSeq [];;

val um : Umap<int,int>

> let um2 = Umap.add 0 0 um;;

val um2 : Umap<int,int>

> Umap.toSeq um;;
val it : seq<int * int> = [|(0, 0)|]
```
Here we would expect `um` to be empty, but it has (0,0) also.

**Comment by bryanedds** [comment]
Integrated manually. Thanks!

**Pull request closed without merging**
