### PR TITLE
improvement to nuedit to show what .exe it is loading from

### PR DESCRIPTION
**Pull request by ImaginaryDevelopment**

### CODE REVIEW

**Comment by bryanedds** [comment]
Sorry I haven't followed up on this - it'll be going in today if it still works :)

**Comment by ImaginaryDevelopment** [comment]
I'm guessing it didn't still work? =( and you left twitter, I had some of your tweets favorited that appear to be lost now =(

**Comment by bryanedds** [comment]
Sorry, I have yet to get back to this one. Since so much has changed in the repository, I'm going to have to integrate this manually.

**Comment by bryanedds** [comment]
Sorry, I took way too long to do this... Closing :(

**Pull request closed without merging**
