### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by bryanedds** [comment]
This MR actually raises several issues -

1) Should we instead put this type of documentation in Nu.Documentation?

2) Should we also instead go ahead and painstakingly convert Nu.Documentation from ODS to mark-up?

The answer to both of these questions is probably yes, so that's why this MR probably won't make it in.

**Comment by Happypig375** [comment]
@bryanedds I edited the files to remove adding a new file, instead utilising the ReadMe. This should serve the purpose better without introducing inconsistent documentation formats.

**Comment by bryanedds** [comment]
Ya, this is better. It solves your issue without opening a can of worms.

Once I get back to it, I will merge this and make some modifications to yours (it also needs to at least mention the world editor Nu.Gaia in the Nu folder).

**Comment by bryanedds** [comment]
There's really no utility for this PR anymore, so I will close it.

**Pull request closed without merging**
